name: Deploy Frontend to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy static files to Azure Blob
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
            --destination \$web \
            --source . \
            --overwrite \
            --auth-mode key \
            --account-key $(az storage account keys list \
                --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
                --resource-group ${{ secrets.RESOURCE_GROUP }} \
                --query [0].value -o tsv)
