name: Frontend Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy-to-azure:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login via Service Principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          auth-type: SERVICE_PRINCIPAL

      - name: Deploy Bicep files to resource group
        run: |
          az deployment group create \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --template-file ./bicep/main.bicep \
            --parameters storageAccountName=${{ secrets.STORAGE_ACCOUNT_NAME }}
