name: Frontend Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write      # Required for OIDC token
  contents: read       # Required to checkout repo code

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: 'ID_TOKEN'  # Use ID_TOKEN for OIDC login

      - name: Deploy Bicep template
        run: |
          az deployment group create \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --template-file bicep/main.bicep \
            --parameters storageAccountName=${{ secrets.STORAGE_ACCOUNT_NAME }}

