name: Frontend Deployment

on:
  push:
    branches:
      - main

permissions:
  id-token: write        # Required for OIDC authentication
  contents: read         # Allows checkout and read of repo contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Azure Login with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          # OIDC uses ID token automatically with v2 — no need to specify auth-type

      - name: Deploy Bicep to Azure
        uses: azure/cli@v2
        with:
          inlineScript: |
            az deployment group create \
              --resource-group ${{ secrets.RESOURCE_GROUP }} \
              --template-file bicep/main.bicep \
              --parameters storageAccountName=${{ secrets.STORAGE_ACCOUNT_NAME }}
